replicaCount: 1
image:
  repository: benchrs
  pullPolicy: IfNotPresent
  tag: ""
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 8080
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
